
###
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "email": "email@maiugul12331.com",
    "password": "password",
    "firstName": "firstName",
    "lastName": "lastName",
    "phoneNumber": "phoneNumber",
    "gender": 1,
    "country": "country",
    "age": "2021-03-17T08:29:29.968Z"
}

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "email@mail12331.com",
    "password": "password" 
}

###
POST http://localhost:3000/api/project/create
content-type: application/json

{
  "ownerId": "1111ccc1",
   "title": "Test create",
   "description": "This is a great project! I really like it!",
   "isOpen":true,
   "estimateMin": 1,
   "estimateMax": 1,
    "features": [{
            "level": "1",
            "title": "Feature login",
            "description": "1",
            "isRequired": true,
            "estimateMin": 1,
            "estimateMax": 1
         },
          {
             "level": "1",
             "title": "Not found",
             "description": "1",
             "isRequired": true,
             "estimateMin": 1,
             "estimateMax": 1
          },
         {
            "level": "1",
            "title": "Feature login",
            "description": "1",
            "isRequired": true,
            "estimateMin": 1,
            "estimateMax": 1
         }
         ]


}

###
GET http://localhost:3000/api/project/get?id=6062f5f12deccf2f18bbe95d



###
DELETE http://localhost:3000/api/project/delete?id=6062fe85d9fcbc14dc9f7a10


###
PUT http://localhost:3000/api/project/update                           
content-type: application/json

{
    "_id":"6062fea4d9fcbc14dc9f7a14",
     "ownerId": "asdfasdasdasdasd",
   "title": "Test",
   "description": "This is a great project! I really like it!",
   "isOpen":true,
   "estimateMin": 1,
   "estimateMax": 1,
    "features": [{
        "level":"1",
"title":"1",
"description":"1",
"isRequired":true,
"estimateMin":1,
"estimateMax":1
    }]
}



//!search 
###
POST http://localhost:3000/api/project/search
content-type: application/json

{
    "page": 2,
    "searchText": "r",
    "pageSize" : 3


}


//Agreggation
###
GET http://localhost:3000/api/project/search_feature?search=Feature login


