
###
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "email": "email@maiugul12331.com",
    "password": "password",
    "firstName": "firstName",
    "lastName": "lastName",
    "phoneNumber": "phoneNumber",
    "gender": 1,
    "country": "country",
    "age": "2021-03-17T08:29:29.968Z"
}

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "email@mail12331.com",
    "password": "password" 
}

###
POST http://localhost:3000/api/project/create
content-type: application/json

{
  "ownerId": "string",
   "title": "string",
   "description": "string",
   "isOpen": "boolean",
   "estimateMin": "number",
   "estimateMax": "number",
    "features": "FeatureModel[]"


}
