POST http://localhost:3000/api/example/test
content-type: application/json

{
    "test": "Test"
}
###
POST http://localhost:3000/api/example/test
content-type: application/json

{
    "email": "email",
    "password": "password",
    "firstName": "firstName",
    "lastName": "lastName",
    "phoneNumber": "phoneNumber",
    "gender": "gender",
    "country": "country",
    "age": "age",
}